on:
  push:
    branches:
      - main
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3.4.2
        with: 
          dotnet-version: '10.0.x'

      - name: Grant execution permission to test.sh
        run: chmod +x ./src/test.sh

      - name: Run Bash test script
        run: ./src/test.sh
